name: Integration Test
on:
  workflow_dispatch:
  schedule:
    - cron: "36 20 * * 0"
  pull_request_target:
    types: [labeled]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.label.name }}
  cancel-in-progress: true
jobs:
  integration:
    # Run only on manual, schedule trigger or when 'integration-test' label is added
    if: github.event_name != 'pull_request_target' || github.event.label.name == 'integration-test'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: 'read'
      pull-requests: 'write'
      id-token: 'write'
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        workload_identity_provider: projects/195438090918/locations/global/workloadIdentityPools/deck-integration/providers/github
        service_account: deck-integration-test@braided-shift-468913-t8.iam.gserviceaccount.com
    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@b94431e051d1c52dcbe9a7092a4f10f827795416 # v2.1.0
      with:
        chrome-version: stable
    - name: Run integration tests
      env:
        DECK_TEST_FOLDER_ID: '0AIEL8jopnJdRUk9PVA'
        DECK_ENABLE_ADC: "true"
      run: |
        make fulltest
    - name: Run octocov
      uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
      with:
        config: .octocov-full.yml
